language: go

go:
  - 1.14.x

install:
  - go get github.com/bostontrader/okprobe

script:
  - git clone https://github.com/bostontrader/okcatbox
  - cd okcatbox
  - go build
  - ./okcatbox
  - ./okcatbox -help

  - ./travis-script.sh