language: go

go:
  - 1.14.x

install:
  - go get github.com/bostontrader/okprobe

script:
  - git clone https://github.com/bostontrader/okcatbox
  - cd okcatbox
  - go build
  - ./okcatbox
  - ./okcatbox -help
  - ./okcatbox -config=okcatbox.yaml &

  - CATBOX_URL=http://localhost:8090

  # These credentials are unique to the Catbox
  - CATBOX_CREDENTIALS=okcatbox-read.json
  - curl -X POST $CATBOX_URL/credentials --output $CATBOX_CREDENTIALS

  # funding
  - okprobe -url $CATBOX_URL -errors -keyfile $CATBOX_CREDENTIALS -endpnt currencies
  - okprobe -url $CATBOX_URL -errors -keyfile $CATBOX_CREDENTIALS -endpnt deposit-address
  - okprobe -url $CATBOX_URL -errors -keyfile $CATBOX_CREDENTIALS -endpnt deposit-history
  - okprobe -url $CATBOX_URL -errors -keyfile $CATBOX_CREDENTIALS -endpnt wallet
  - okprobe -url $CATBOX_URL -errors -keyfile $CATBOX_CREDENTIALS -endpnt withdrawalfee

  # spot
  - okprobe -url $CATBOX_URL -errors -keyfile $CATBOX_CREDENTIALS -endpnt accounts